services:
    application:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: application
        container_name: application
        tty: true
        ports:
            - "9090:9000"
        volumes:
            - .:/var/www
        networks:
            - laravel_app
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_app
networks:
    laravel_app:
